### ISSUE TITLE
Changes from ubuntu 16.04 to 18.04

### ISSUE THREAD

**Issue by unbeforkinglievable** [esell/deb-simple#30]
It seems that Bionic Beaver (18.04) requires more fields than Xenial (16.04) in the Packages.gz file...
This worked on Xenial:
`
Filename: dists/xenial/main/binary-amd64/<name>_<version>_amd64.deb
Size: <size>
MD5sum: <md5>
SHA1: <sha>
SHA256: <sha>
`

But does not work on Bionic;  I added these lines to the extracted file at /var/lib/apt/lists/:
`
Package: <name>
Architecture: amd64
Version: <version>
Priority: standard
Description: <description>
`
And it worked fine.

This may be an issue with my debian packaging tool, not necessarily an issue with deb-simple, but just thought you might want to know.

**Comment by dig412** [comment]
@unbeforkinglievable I think this issue is fixed in master - all Packages files require those fields but `deb-simple` wasn't copying them in some cases depending on how the control file archive had been build.

This was fixed in #31 by kshvakov.

@esell Could you create a new release from master?

**Comment by esell** [comment]
@dig412, done! v1.4.1 was just published off of master.

**Comment by MikeCollinsOnt** [comment]
I'm using v1.4.1 and I'm still seeing this problem, on 18.04 (bionic) only.

**Comment by MikeCollinsOnt** [comment]
The above comment applies to a package I build on 18.04.  If, instead, I:

- rebuild my "bionic" package on a 16.04 Docker image
- push the rebuilt package to the deb-simple repo in an 18.04 Docker image

then the control file is found, and the full package info is correctly entered into the Packages.gz file.

**Comment by MikeCollinsOnt** [comment]
@esell Would it be more helpful if I submitted a new issue for this?

**Comment by dig412** [comment]
@MikeCollinsOnt Would you be able to build a test package on 18.04 and upload it somewhere for me to investigate with? The file contents don't matter - it's almost certainly an issue with the metadata.

**Comment by esell** [comment]
apologies on the delay folks. @MikeCollinsOnt, i think it is ok to just piggyback on this issue. if you want to post up the metadata files as @dig412 suggested that would help (gist, pastebin, etc).

**Comment by MikeCollinsOnt** [comment]
@esell @dig412 Thanks for the responses.  I've not been able to get back to looking at this, but hopefully I'll get the opportunity to get something to you soon.
